### ISSUE TITLE
how can i call the Function use mdk?

### ISSUE THREAD

**Issue by yuanfeng-net** [Spuckwaffel/MDKTest#2]
how can i call the Function use mdk?

like AFortPlayerControllerAthena.WriteCreateBuildingAnalytics

![image](https://github.com/Spuckwaffel/MDK-Lib/assets/19276615/ab228b2f-9f49-4ec0-bb4a-90de55b0993a)

**Comment by Spuckwaffel** [comment]
MDKs are mostly targeting external users, it's not really made to call functions. However in your case the function doesn't really take any params, you can call it via the given memory address offset.

**Comment by yuanfeng-net** [comment]
Can you give me a demo of calling a parameterless method?

**Comment by Spuckwaffel** [comment]
hey there, this is not an MDK lib related request and your answer can be easily found on stackoverflow.
