### ISSUE TITLE
Double free with the destructor if cache is set to false.

### ISSUE THREAD

**Issue by Sevenn83** [Spuckwaffel/MDKTest#4]
In this example :

```cpp
if (true) {
    USceneComponent rootComponentLocalPlayer = MDKHandler::get<USceneComponent, UActorComponent>(rootComponentPtr, false);
}
```

The destructor of MDKBase is going to be called once after the execution of get<>(); and once again at the end of the if statement, since `USceneComponent rootComponentLocalPlayer` also inherits from MDKBase.

The destructor is going to try to free the same block.blockPointer twice, which leads to a crash. 
https://github.com/Spuckwaffel/MDK-Lib/blob/c1ae7ed518df07967d1d5884b97582d666894112/SDKTest/MDK.cpp#L25-L32

I haven’t really figured out the best way to work around this issue, so I’ve just commented out the content of the destructor, but I don’t feel it’s a great idea, even if I didn’t see any negative impact on the memory.

**Comment by Spuckwaffel** [comment]
hmmm i wonder why the destructor gets called twice? can you provide more code or a copy paste example when this happens? This doesn't look normal

**Comment by Sevenn83** [comment]
I've reproduce the exact same function that I got, I've just striped every irrelevant code
```cpp
void MyClass::getPlayers()
{
    while(running)
    {
        std::vector<radarElement> tmp;

        radarElement elementLocal;

        APawn* pawnPtr =
            MDKHandler::readSingle<APlayerController, APawn*>(_playerControllerPtr, &APlayerController::AcknowledgedPawn);
        if (!pawnPtr)
            continue;

        USceneComponent* rootComponentPtr =
            MDKHandler::readSingle<APawn, USceneComponent*>(pawnPtr, &APawn::RootComponent);

        USceneComponent rootComponentLocalPlayer = MDKHandler::get<USceneComponent, UActorComponent>(rootComponentPtr, false);

        _localRelativeLocation = rootComponentLocalPlayer.RelativeLocation<FVector>();
        _localRelativeRotation = rootComponentLocalPlayer.RelativeRotation<FRotator>();

        elementLocal.color = IM_COL32(0, 255, 0, 255);
        elementLocal.x = _localRelativeLocation.X();
        elementLocal.y = _localRelativeLocation.Y());
        elementLocal.name = "ME";

        tmp.push_back(elementLocal);

        cache::getRadarPlayerElements.clear();
        cache::getRadarPlayerElements = tmp;

        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }
}
```

In this function after inspecting with the debuger, the destructor is called directly after the MDKHandler::get execution and one more time at the end of the loop because end of the scope of USceneComponent rootComponentLocalPlayer.

**Comment by Spuckwaffel** [comment]
check out the newest commit, i think ive fixed it.

**Comment by Sevenn83** [comment]
Yep, the last commit fix the problem 🙏
Thank you.
